module(
    name = "simple_cuda_info",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_cuda", version = "0.3.0")
bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "toolchains_llvm", version = "1.7.0")

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    name = "llvm_toolchain",
    cxx_standard = {"": "c++26"},
    llvm_version = "20.1.8",
    stdlib = {"": "builtin-libc++"},
)
use_repo(llvm, "llvm_toolchain", "llvm_toolchain_llvm")
register_toolchains("@llvm_toolchain//:all")

cuda = use_extension("@rules_cuda//cuda:extensions.bzl", "toolchain")
cuda.redist_json(
    name = "cuda_13_2_1",
    components = [
        "cccl",
        "crt",
        "culibos",
        "cudart",
        "nvcc",
        "nvvm",
    ],
    version = "13.2.1",
)
cuda.toolkit(name = "cuda")
use_repo(cuda, "cuda")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "distroless_cc_debian12",
    digest = "sha256:bd2899c12b335c827750ccf2359879eab09c09b206023dcebea408947d54127c",
    image = "gcr.io/distroless/cc-debian12",
    platforms = ["linux/amd64"],
)
use_repo(
    oci,
    "distroless_cc_debian12",
    "distroless_cc_debian12_linux_amd64",
)

register_toolchains(
    "@cuda//toolchain/clang:clang-local-toolchain",
    "@cuda//toolchain:nvcc-local-toolchain",
    "@cuda//toolchain/disabled:disabled-local-toolchain",
)
